- name: Install MySQL server
  ansible.builtin.dnf:
    name: mysql-server
    state: latest

- name: Start MySQL server
  ansible.builtin.service:
    name: mysqld
    enabled: yes

- name: Enable MySQL server
  ansible.builtin.service:
    name: mysqld
    enabled: yes

- name: install python mysql dependencies
  ansible.builtin.pip:
    name: 
    - PyMySQL
    - cryptography
    executable: pip3.9

- name: check DB connection
  community.mysql.mysql_info:
    login_user: root
    login_password: "{{PASSWORD}}"
    login_host: "{{login_host}}"
    filter: version
  ignore_errors: yes
  register: mysql_connection_output

- name: print the output
  ansible.builtin.debug:
    msg: "output: {{mysql_connection_output}}"

- name: setup root password
  ansible.builtin.command: "mysql_secure_installation --set-root-pass {{PASSWORD}}"
  when: mysql_connection_output.failed is true